{{- if .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.existingSecretName }}
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.usernameKey }}: {{ .Values.database.devUsername | quote }}
  {{ .Values.database.passwordKey }}: {{ .Values.database.devPassword | quote }}
{{- end }}
