replicaCount: 2

image:
  repository: api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8080

routes:
  productServiceUri: http://product-service
  orderServiceUri: http://order-service

cors:
  allowedOrigins: http://localhost:5173

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: 1

serviceAccount:
  create: true
  name: ""

istio:
  enabled: true
  destinationRule:
    connectionPool:
      tcp:
        maxConnections: 200
      http:
        http1MaxPendingRequests: 200
        maxRequestsPerConnection: 20
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
podAnnotations: {}
podLabels: {}
topologySpreadConstraints: []
