{{- if and .Values.istio.enabled .Values.istio.gateway.create }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.global.istio.gatewayName }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.global.hostname | quote }}
      {{- if .Values.global.tls.enabled }}
      tls:
        httpsRedirect: true
      {{- end }}
    {{- if .Values.global.tls.enabled }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ .Values.global.hostname | quote }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.global.tls.credentialName }}
    {{- end }}
{{- end }}
